spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    hikari:
      idle-timeout: 1800000
      minimum-idle: 3
      max-lifetime: 30000
      maximum-pool-size: 10
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yangluyao.easyexcel.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true